/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        paper: 'var(--wb-paper)',
        surface: 'var(--wb-surface)',
        sunken: 'var(--wb-sunken)',
        line: 'var(--wb-line)',
        'line-bold': 'var(--wb-line-bold)',
        ink: {
          900: 'var(--wb-ink-900)',
          700: 'var(--wb-ink-700)',
          500: 'var(--wb-ink-500)',
          400: 'var(--wb-ink-400)',
          300: 'var(--wb-ink-300)',
          200: 'var(--wb-ink-200)',
        },
        accent: {
          900: 'var(--wb-accent-900)',
          700: 'var(--wb-accent-700)',
          500: 'var(--wb-accent-500)',
          300: 'var(--wb-accent-300)',
          100: 'var(--wb-accent-100)',
          50: 'var(--wb-accent-50)',
        },
        teal: {
          700: 'var(--wb-teal-700)',
          500: 'var(--wb-teal-500)',
          300: 'var(--wb-teal-300)',
          100: 'var(--wb-teal-100)',
        },
        alert: {
          'low-bg': 'var(--wb-alert-low-bg)',
          'low-fg': 'var(--wb-alert-low-fg)',
          'low-border': 'var(--wb-alert-low-border)',
          'high-bg': 'var(--wb-alert-high-bg)',
          'high-fg': 'var(--wb-alert-high-fg)',
          'high-border': 'var(--wb-alert-high-border)',
        },
        status: {
          'open-bg': 'var(--wb-status-open-bg)',
          'open-fg': 'var(--wb-status-open-fg)',
          'seen-bg': 'var(--wb-status-seen-bg)',
          'seen-fg': 'var(--wb-status-seen-fg)',
          'contacted-bg': 'var(--wb-status-contacted-bg)',
          'contacted-fg': 'var(--wb-status-contacted-fg)',
          'closed-bg': 'var(--wb-status-closed-bg)',
          'closed-fg': 'var(--wb-status-closed-fg)',
        },
      },
      fontSize: {
        micro: ['11px', '1.4'],
        caption: ['13px', '1.45'],
        body: ['16px', '1.55'],
        'body-lg': ['17px', '1.55'],
        h3: ['18px', '1.4'],
        h2: ['22px', '1.3'],
        h1: ['28px', '1.3'],
        energy: ['72px', '1'],
      },
      fontFamily: {
        sans: ['Heebo', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '32px',
        '3xl': '48px',
      },
      // Pulse v5 uses larger rounding
      borderRadius: {
        sm: '10px',
        md: '14px',
        lg: '20px',
        xl: '28px',
        pill: '999px',
        battery: '24px',
      },
      boxShadow: {
        sm: 'var(--wb-shadow-sm)',
        md: 'var(--wb-shadow-md)',
        lg: 'var(--wb-shadow-lg)',
        focus: 'var(--wb-shadow-focus)',
      },
    },
  },
  plugins: [],
}
